### ISSUE TITLE
Can you add icon support to MenuGroup?

### ISSUE THREAD

**Issue by scramatte** [dcasia/collapsible-resource-manager#101]
Hi,

Can you add icon support to MenuGroup?

Regards

**Comment by milewski** [comment]
The Laravel Nova class `Laravel\Nova\Menu\MenuGroup` does not provide any way to return metadata to the frontend like the `MenuItem` does.

While this change is very easy to do, it would require creating a custom `MenuGroup` class, which, in turn, would necessitate users importing the `MenuGroup` class from this package instead of the Nova one. This could potentially be confusing. So, I believe it's better not to have this feature, or you can request the Laravel Nova team to include the `Metable` trait in all these menu classes, enabling us to achieve more sophisticated functionality.
