### ISSUE TITLE
Link to a resource on root section click 

### ISSUE THREAD

**Issue by scramatte** [dcasia/collapsible-resource-manager#103]
Hi,

I would like to link root section click to a resources.
For example, if  the root section is service desk , I would like to toggle the submenu and redirect to tickets list for example or dashboard or anything else.

Regards

**Comment by milewski** [comment]
You can already do it, you just need to call `->path()` on the root `MenuSection`

You can refer to this section from nova documentation: https://nova.laravel.com/docs/customization/menus.html#menu-sections

![image](https://github.com/dcasia/collapsible-resource-manager/assets/2874967/a640b8c6-4f94-497c-bce9-69c9fa6806c2)

**Comment by scramatte** [comment]
Hi,
It doesn't works if you have MenuGroup or MenuItem inside

**Comment by milewski** [comment]
Yes, if you have items inside the menu, it understands that you want them to expand when clicking, instead of navigating when clicking. I believe what you're asking for is for it to both expand and navigate simultaneously, but this could be unusual because the UI would flicker during navigation, affecting the smoothness of the expanding animation
